from time import *
print("challenge one - the wrong name")
sleep(2)
print("let's see our original list...")
sleep(2)
phigros = ["green", "blue", "yellow", "genshin", "red", "orange", "black"]
print(phigros)
sleep(2)
print("why is genshin here??? Lets change it!")
sleep(1)
print("-after a while-")
sleep(3)
phigros[3] = "Purple"
print(phigros)
sleep(2)
print("Yep, that looks way better!")
sleep(4)
print("challenge two - the secrete message")
sleep(2)
unc0ver = ["hi", "what", "my", "are", "name", "you", "is", "doing", "slim", "today?", "shaby"]
print(unc0ver)
sleep(2)
print("Tom：what is that!")
sleep(2)
print("Tom：Oh hey, I know! is a secrete message, lets try to make a sentence with it!")
sleep(4)
unc0ver.remove('what')
unc0ver.remove('are') 
unc0ver.remove('you') 
unc0ver.remove('doing')
unc0ver.remove('today?')
print(unc0ver)
sleep(2)
print("Tom：It's saying hi my name is slim shady")
sleep(2)
print("Tom：But there are other word, can they also make a sentence??? let's see...")
sleep(4)
unc0ver = ["hi", "what", "my", "are", "name", "you", "is", "doing", "slim", "today?", "shaby"]
unc0ver.remove('hi')
unc0ver.remove('my') 
unc0ver.remove('name') 
unc0ver.remove('is')
unc0ver.remove('slim')
unc0ver.remove('shaby')
print(unc0ver)
sleep(2)
print("Tom：It's saying what are you doing today???")
sleep(2)
print("well, I guess just another day of python...")
sleep(4)
print("challenge three - unknown codes")
sleep(2)
Macos = ["Mike", "", "Emma", "Kelly", "", "Brad"]
print("naughty kids just put empty strings again??? let's remove it!")
sleep(4)
linux = [string for string in Macos if string != ""]
print(linux)
sleep(2)
print("Easy!")
sleep(4)
print("That's all thanks！")


